name: widget-server pipe

on:
  push:
    branches:
      - "master"

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to AWS ECR
        id: login-to-aws-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push the image to AWS ECR
        id: build-and-push-image
        run: |
          docker build -t docker-nlv3-ftr:v3 .
          docker tag docker-nlv3-ftr:v3 403429280851.dkr.ecr.us-wast-2.amazonaws.com/rocketseat/docker-nlv3-ftr:v3
          docker push 403429280851.dkr.ecr.us-wast-2.amazonaws.com/rocketseat/docker-nlv3-ftr:v3
