name: widget-server pipe

on:
  push:
    branches:
      - "master"

env:
  ECR_REPOSITORY: "rocketseat/widget-server"

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to AWS ECR
        id: login-to-aws-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push the image to AWS ECR
        id: build-and-push-image
        env:
          ECR_REGISTRY: ${{ steps.login-to-aws-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
        run: |
          docker build -t docker-nlv3-ftr:v3 .
          docker tag docker-nlv3-ftr:v3 $ECR_REGISTRY/$ECR_REPOSITORY:v3
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:v3
